#!/bin/sh
cat <<EOF
uci_del_type firewall redirect
echo "uci import firewall.@redirect[x]"
uci -m import firewall <<UCI
EOF

cat ${0#?????}.conf

cat <<EOF
UCI
uci_commit firewall
service reload firewall 2>/dev/null
EOF
