#!/bin/sh
set -ex
git pull --rebase
./scripts/feeds update -a
./scripts/feeds install \
  adblock ddns-scripts miniupnpd shadowsocks-libev sqm-scripts unbound watchcat \
  tmux wget \
  aircrack-ng airmon-ng procps-ng-ps
cat >.config <<EOF
CONFIG_TARGET_ar71xx=y
CONFIG_TARGET_ar71xx_generic=y
CONFIG_TARGET_ar71xx_generic_DEVICE_mw4530r-v1=y

CONFIG_PACKAGE_ca-certificates=y
CONFIG_PACKAGE_curl=y
# CONFIG_PACKAGE_dnsmasq is not set
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_dnsmasq_full_ipset=y
# CONFIG_PACKAGE_dnsmasq_full_auth is not set
# CONFIG_PACKAGE_dnsmasq_full_conntrack is not set
# CONFIG_PACKAGE_dnsmasq_full_dhcpv6 is not set
# CONFIG_PACKAGE_dnsmasq_full_dnssec is not set
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_uhttpd=y

CONFIG_PACKAGE_adblock=y
CONFIG_PACKAGE_ddns-scripts=y
CONFIG_PACKAGE_miniupnpd=y
CONFIG_PACKAGE_shadowsocks-libev=y
CONFIG_PACKAGE_sqm-scripts=y
CONFIG_PACKAGE_unbound=y
CONFIG_PACKAGE_watchcat=y

CONFIG_PACKAGE_tmux=y
CONFIG_PACKAGE_wget=y

CONFIG_PACKAGE_aircrack-ng=y
CONFIG_PACKAGE_airmon-ng=y
CONFIG_PACKAGE_procps-ng=y
CONFIG_PACKAGE_procps-ng-ps=y
# CONFIG_PACKAGE_procps-ng-free is not set
# CONFIG_PACKAGE_procps-ng-kill is not set
# CONFIG_PACKAGE_procps-ng-pgrep is not set
# CONFIG_PACKAGE_procps-ng-pkill is not set
# CONFIG_PACKAGE_procps-ng-pmap is not set
# CONFIG_PACKAGE_procps-ng-pwdx is not set
# CONFIG_PACKAGE_procps-ng-skill is not set
# CONFIG_PACKAGE_procps-ng-slabtop is not set
# CONFIG_PACKAGE_procps-ng-snice is not set
# CONFIG_PACKAGE_procps-ng-tload is not set
# CONFIG_PACKAGE_procps-ng-top is not set
# CONFIG_PACKAGE_procps-ng-uptime is not set
# CONFIG_PACKAGE_procps-ng-vmstat is not set
# CONFIG_PACKAGE_procps-ng-w is not set
# CONFIG_PACKAGE_procps-ng-watch is not set
EOF
make defconfig
./scripts/diffconfig.sh
make -j12
