#!/bin/sh
set -ex

if [ x"$1" = x"-u" ]; then
    git pull --rebase origin master
    cp feeds.conf.default feeds.conf
    ./scripts/feeds update -a
    for dir in $(awk '/^src-git / {print $2}' feeds.conf)
    do
        cd "feeds/$dir"
        git rebase origin/master
        cd ../../
    done
fi

./scripts/feeds install diffutils ethtool sqm-scripts

cat >.config <<EOF
CONFIG_KERNEL_KALLSYMS=y
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_zbt-wg3526=y

CONFIG_PACKAGE_kmod-sched-cake=y

CONFIG_PACKAGE_diffutils=y
CONFIG_PACKAGE_ethtool=y
# CONFIG_PACKAGE_wpad-mini is not set
CONFIG_PACKAGE_wpad=y
CONFIG_PACKAGE_sqm-scripts=y

CONFIG_WPA_MSG_MIN_PRIORITY=1
EOF
make defconfig
./scripts/diffconfig.sh
make -j12
