#!/bin/sh
set -ex
git pull --rebase
./scripts/feeds update -a
./scripts/feeds install \
  tmux wget \
  aircrack-ng airmon-ng procps-ng-ps \
  ettercap dsniff
cat >.config <<EOF
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_zbt-wg3526=y

CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_tcpdump=y

CONFIG_PACKAGE_tmux=y
CONFIG_PACKAGE_wget=y

CONFIG_PACKAGE_aircrack-ng=y
CONFIG_PACKAGE_airmon-ng=y
CONFIG_PACKAGE_procps-ng=y
CONFIG_PACKAGE_procps-ng-ps=y
# CONFIG_PACKAGE_procps-ng-free is not set
# CONFIG_PACKAGE_procps-ng-kill is not set
# CONFIG_PACKAGE_procps-ng-pgrep is not set
# CONFIG_PACKAGE_procps-ng-pkill is not set
# CONFIG_PACKAGE_procps-ng-pmap is not set
# CONFIG_PACKAGE_procps-ng-pwdx is not set
# CONFIG_PACKAGE_procps-ng-skill is not set
# CONFIG_PACKAGE_procps-ng-slabtop is not set
# CONFIG_PACKAGE_procps-ng-snice is not set
# CONFIG_PACKAGE_procps-ng-tload is not set
# CONFIG_PACKAGE_procps-ng-top is not set
# CONFIG_PACKAGE_procps-ng-uptime is not set
# CONFIG_PACKAGE_procps-ng-vmstat is not set
# CONFIG_PACKAGE_procps-ng-w is not set
# CONFIG_PACKAGE_procps-ng-watch is not set

CONFIG_PACKAGE_ettercap=y
CONFIG_PACKAGE_dsniff=y
EOF
make defconfig
./scripts/diffconfig.sh
make -j12
