#!/bin/sh
set -ex

if [ x"$1" = x"-u" ]; then
    git pull --rebase
    cp feeds.conf.default feeds.conf
    # echo 'src-git luci2 https://github.com/jow-/luci-ng.git' >> feeds.conf
    ./scripts/feeds update -a
    for dir in $(awk '/^src-git / {print $2}' feeds.conf)
    do
        cd "feeds/$dir"
        git rebase origin/master
        cd ../../
    done
fi

./scripts/feeds install \
  diffutils
  # luci2-ui-base

cat >.config <<EOF
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_zbt-wg3526=y

# CONFIG_PACKAGE_wpad-mini is not set
CONFIG_PACKAGE_wpad=y
CONFIG_WPA_MSG_MIN_PRIORITY=1
CONFIG_WPA_SUPPLICANT_OPENSSL=y

CONFIG_PACKAGE_diffutils=y
EOF
# CONFIG_PACKAGE_luci2-ui-base=y
make defconfig
./scripts/diffconfig.sh
make -j12
