#!/bin/sh
set -eu

opkg_update() {
    if [ "$(find /var/opkg-lists/ -type f | wc -l)" -eq 0 ]; then
        echo 'opkg update'
        opkg update
    fi
}

opkg_installed() {
    opkg status "$1" | grep -q installed
}

opkg_install() {
    local package package_name
    for package in "$@"
    do
        package_name="$(basename "$package")"
        package_name="${package_name%.*}"
        package_name="${package_name%%_*}"
        if ! opkg_installed "$package_name"; then
            opkg_update
            echo "opkg install $package"
            opkg install "$package"
            if [ x"${package::1}" = x'/' ]; then
                rm -f "$package"
            fi
        fi
    done
}

opkg_remove() {
    local package
    package="$1"
    if opkg_installed "$package"; then
        echo "opkg remove $package"
        opkg --autoremove remove "$package"
    fi
}

uci_exists() {
    local config
    config="$1"
    uci -q get "$config" >/dev/null
}

# XXX: not work if value contain space
uci_add_list() {
    local key value
    key="$1"
    shift
    for value in "$@"
    do
        if ! uci -q -d '
' get "$key" | grep -qxF "$value"; then
            uci add_list "$key=$value"
        fi
    done
}

uci_del_list() {
    local key value
    key="$1"
    shift
    for value in "$@"
    do
        uci del_list "$key=$value"
    done
}

uci_commit() {
    local config
    config="$1"
    if ! uci_exists "$config"; then
        return 2
    fi
    if config_changed "$config"; then
        echo
        echo "uci changes:"
        uci changes "$config"
        echo
        uci commit
        update_md5sums
        return 0
    else
        rm -f "/var/.uci/$config"
        return 1
    fi
}

uci_delete() {
    local config
    for config in "$@"
    do
        if uci_exists "$config"; then
            uci delete "$config"
        fi
    done
}

uci_del_type() {
    local config type deleted
    config="$1"
    type="$2"
    deleted="0"
    while uci -q delete "${config}.@${type}[-1]"
    do
        deleted=$((deleted+1))
    done
}

uci_rename() {
    local key value
    key="$1"
    value="$2"
    if uci_exists "$key"; then
        uci rename "$key=$value"
    fi
}

service() {
    local action service config
    action="$1"
    service="$2"
    config="${3:-$service}"
    if [ ! -e "/etc/init.d/$service" ]; then
        return 0
    fi
    case "$action" in
        reload|restart)
            if [ x"$config" = x'-' ] || uci_commit "$config"; then
                echo "service $action $service"
                "/etc/init.d/$service" "$action" || true
            fi
            ;;
        enable)
            if ! "/etc/init.d/$service" enabled; then
                echo "service $action $service"
                "/etc/init.d/$service" "$action" || true
            fi
            ;;
        *)
            echo "service $action $service"
            "/etc/init.d/$service" "$action" || true
            ;;
    esac
}

add_cron() {
    local name cron cron_file
    name="$1"
    cron="$2"
    user="${3:-root}"
    cron_file="/etc/crontabs/${user}"
    if [ ! -e "$cron_file" ] || ! grep -qxF "$cron" "$cron_file"; then
        test -e "$cron_file" && sed -i -e "/^# ${name}\$/,+1d" "$cron_file"
        echo "cron-${name}: $cron"
        echo -e "# ${name}\n${cron}" >> "$cron_file"
        /etc/init.d/cron start
    fi
}

hr() {
    printf '%s\n' ------------------------------------------------------------
}

md5sum_file() {
    local file
    file="$1"
    md5sum "$file" | cut -d' ' -f1
}

move() {
    local src dest
    src="$1"
    dest="$2"
    if [ x"$(md5sum_file "$src")" != x"$(md5sum_file "$dest")" ]; then
        echo "move: $src -> $dest"
        mv "$src" "$dest"
    else
        rm "$src"
        return 1
    fi
}

remove (){
    local file
    for file in "$@"
    do
        if [ -f "$file" ]; then
            echo "remove $file"
            rm "$file"
        fi
    done
}

update_md5sums() {
    md5sums="$(md5sum /etc/config/*)"
}

md5sum_config() {
    local config
    config="$1"
    echo "$md5sums" | grep -F " /etc/config/${config}" | cut -d' ' -f1
}

md5sum_uci() {
    local config
    config="$1"
    uci export "$config" | grep -v '^package '| md5sum | cut -d' ' -f1
}

config_changed() {
    local config
    config="$1"
    [ x"$(md5sum_config "$config")" != x"$(md5sum_uci "$config")" ]
}

strip_comment() {
    sed -e '/^\s*$/d' -e '/^\s*#/d'
}

uci_batch_set() {
    local config
    config="$1"
    echo "$config" | strip_comment | sed -e 's/^/set /' | uci batch
}

md5sums=''
update_md5sums
