#!/bin/sh
set -eu

opkg_update() {
    if [ "$(find /var/opkg-lists/ -type f | wc -l)" -eq 0 ]; then
        echo 'opkg update'
        opkg update
    fi
}

opkg_installed() {
    opkg status "$1" | grep -q installed
}

opkg_install() {
    for package in "$@"
    do
        package_name="$(basename "$package")"
        package_name="${package_name%.*}"
        package_name="${package_name%%_*}"
        if ! opkg_installed "$package_name"; then
            opkg_update
            echo "opkg install $package"
            opkg install "$package"
        fi
    done
}

uci_add_list() {
    key="$1"
    shift
    for value in "$@"
    do
        if ! printf "$(uci -q -d '\n' get "$key")" | grep -qxF "$value"; then
            uci add_list "$key=$value"
        fi
    done
}

uci_del_list() {
    key="$1"
    shift
    for value in "$@"
    do
        if printf "$(uci -q -d '\n' get "$key")" | grep -qxF "$value"; then
            uci del_list "$key=$value"
        fi
    done
}

uci_commit() {
    config="$1"
    if ! uci -q get "$config" >/dev/null; then
        return 2
    fi
    if config_changed "$config"; then
        echo "uci changes:"
        uci changes "$config"
        echo
        uci commit
        update_md5sums
        return 0
    else
        rm -f "/var/.uci/$config"
        return 1
    fi
}

uci_delete() {
    for config in "$@"
    do
        if uci -q get "$config" >/dev/null; then
            uci delete "$config"
        fi
    done
}

uci_del_type() {
    config="$1"
    type="$2"
    deleted="0"
    while uci -q delete "${config}.@${type}[-1]"
    do
        deleted=$((deleted+1))
    done
}

service() {
    action="$1"
    service="$2"
    config="${3:-$service}"
    case "$action" in
        reload|restart)
            if uci_commit "$config"; then
                echo "service $action $service"
                "/etc/init.d/$service" "$action"
            fi
            ;;
        *)
            echo "service $action $service"
            "/etc/init.d/$service" "$action"
            ;;
    esac
}

hr() {
    printf '%s\n' ------------------------------------------------------------
}

update_md5sums() {
    md5sums="$(md5sum /etc/config/*)"
}

md5sum_config() {
    config="$1"
    echo "$md5sums" | grep -F " /etc/config/${config}" | cut -d' ' -f1
}

md5sum_uci() {
    config="$1"
    uci export "$config" | grep -v '^package '| md5sum | cut -d' ' -f1
}

config_changed() {
    config="$1"
    [ x"$(md5sum_config "$config")" != x"$(md5sum_uci "$config")" ]
}

md5sums=''
update_md5sums
