#!/bin/bash
# PRE:
# 1) telnet  2) passwd 3) reboot

DEBUG=''
GEN_ONLY='no'
KEEP='rm'
remote_modules="$(ls -1 [1-9][0-9]-*)"
local_modules="$(ls -1 0[0-9]-*)"

settings() {
    local target
    target="$1"
    cat <<EOF

# ----------------------------------------------------------
# Default settings

EOF
    cat default
    cat <<EOF

# ----------------------------------------------------------
# Per device settings

EOF
    if [ -f "$target" ]; then
        cat "$target"
    fi
    if [ -f "${target}.gpg" ]; then
        gpg --batch --no-tty -qd "${target}.gpg"
    fi
    cat <<EOF

# ----------------------------------------------------------

EOF
}

target="$1"
target="${target%.gpg}"
if [ -f "$target" -o -f "${target}.gpg" ]; then
    source <(settings "$target")
    shift
else
    echo "$target and ${target}.gpg not exist"
    exit
fi

scp="scp -pq"
ssh="ssh"
if [ x"$port" != x ]; then
    scp="scp -pqP$port"
    ssh="ssh -p$port"
fi

while getopts ":gh:kl:m:p:x" Option
do
    case "$Option" in
        h) host="$OPTARG" ;;
        g) GEN_ONLY='yes' ;;
        k) KEEP='echo keep remote' ;;
        l)
            local_modules_overrided=1
            local_modules="$OPTARG"
            ;;
        m)
            remote_modules_overrided=1
            remote_modules="$OPTARG"
            ;;
        p) ssh="ssh -p$OPTARG" ;;
        x) DEBUG='-x' ;;
    esac
done

if [ x"$local_modules_overrided" != x ]; then
    if [ x"$remote_modules_overrided" = x ]; then
        remote_modules=''
    fi
elif [ x"$remote_modules_overrided" != x ]; then
    local_modules=''
fi

backup() {
    $ssh "$host" 'sysupgrade --create-backup -' | tar zxf -
}

download() {
    local url basename file
    url="$1"
    basename="$(basename "$url")"
    file="$2"
    if [ x"$file" = x ]; then
        file="files/$basename"
    fi
    if [ ! -e "$file" ]; then
        echo "download: $url -> $file"
        curl -#fSLo "$file" "$url"
    fi
}

push() {
    local src dest md5sum_src md5sum_dest
    src="$1"
    dest="$2"
    if [ ! -e "$src" ]; then
        echo "push: $src does not exist"
        return
    fi
    md5sum_src=$(md5sum "$src" | cut -d' ' -f1)
    md5sum_dest=$($ssh -n "$host" "md5sum $dest 2>/dev/null | cut -d' ' -f1")
    if [ x"$md5sum_src" != x"$md5sum_dest" ]; then
        echo "push: $src -> $dest"
        $scp "$src" "${host}:${dest}"
    fi
}

generate_script() {
    local remote_module
    cat functions
    settings "$target"
    for remote_module in $remote_modules
    do
        cat <<EOF
echo "Begin remote $remote_module"
EOF
        if [ -x "$remote_module" ]; then
            "./$remote_module"
        else
            cat "$remote_module"
        fi
        cat <<EOF
hr

# ----------------------------------------------------------

EOF
    done
}

if [ "$GEN_ONLY" = 'yes' ]; then
    generate_script
    exit
fi

for local_module in $local_modules
do
    echo "Begin local  $local_module"
    if [ x"$DEBUG" != x ]; then
        set -x
    fi
    source "$local_module"
    if [ x"$DEBUG" != x ]; then
        set +x
    fi
    printf '%s\n' ------------------------------------------------------------
done

generate_script | $ssh "$host" 's=/tmp/openwrt-config; cat > $s; chmod 400 $s; sh '$DEBUG' $s; '$KEEP' $s'
