#!/bin/bash
# PRE:
# 1) telnet  2) passwd 3) reboot

DEBUG=''
GEN_ONLY='no'
KEEP='rm'
modules="$(ls -1 [0-9][0-9]-*)"

target="$1"
if [ -f "$target" ]; then
    source "$target"
    shift
else
    echo "$target not exists"
    exit
fi

if [ -f "${target}.gpg" ]; then
    source <(gpg --batch --no-tty -qd "${target}.gpg")
else
    echo "$target.gpg not exist"
fi

ssh_options=''
if [ x"$port" != x ]; then
    ssh_options="-p$port"
fi

while getopts ":gh:km:p:x" Option
do
    case "$Option" in
        h) host="$OPTARG" ;;
        g) GEN_ONLY='yes' ;;
        k) KEEP='echo keep remote' ;;
        m) modules="$OPTARG" ;;
        p) ssh_options="-p$OPTARG" ;;
        x) DEBUG='-x' ;;
    esac
done

backup() {
    ssh "$host" 'sysupgrade --create-backup -' | tar zxf -
}

push() {
    file="$1"
    scp -p "$file" "${host}:/${file}"
}

generate_script() {
    cat functions
    cat <<EOF
# ----------------------------------------------------------
EOF
    for module in $modules
    do
        cat <<EOF
echo "Begin $module"
echo
EOF
        if [ -x "$module" ]; then
            "./$module"
        else
            envsubst < "$module"
        fi
        cat <<EOF
hr
# ----------------------------------------------------------
EOF
    done
}

if [ "$GEN_ONLY" = 'yes' ]; then
    generate_script
    exit
fi

generate_script | ssh $ssh_options "$host" 's=/tmp/openwrt-config; cat > $s; sh '$DEBUG' $s; '$KEEP' $s'
