#!/bin/bash

DEBUG=''

target="$1"
shift

while getopts ":x" Option
do
    case "$Option" in
        x) DEBUG='-x' ;;
    esac
done

source "$target"
port="${port:-22}"

if [ -f "${target}.gpg" ]; then
    source <(gpg -qd "${target}.gpg")
fi

backup() {
    ssh "$host" 'sysupgrade --create-backup -' | tar zxf -
}

push() {
    file="$1"
    scp -p "$file" "${host}:/${file}"
}

generate_script() {
    cat functions
    for module in $modules
    do
        cat <<EOF
hr
echo "Begin $module"
EOF
        envsubst < "$module"
        cat <<EOF
echo "End $module"
EOF
    done
}

generate_script | ssh -p "$port" "$host" 's=/tmp/openwrt-config; cat > $s; sh '$DEBUG' $s; rm $s'
