#!/bin/sh /etc/rc.common

START=93
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/vlmcsd -D -l syslog
    procd_set_param respawn
    procd_set_param user nobody
    procd_close_instance
}
