#!/bin/sh

update_dnsmasq() {
    local conf
    conf=/tmp/dnsmasq.d/99-chn-domains.conf
    if [ "$ACTION" = "ifup" -a ! -e "$conf" ]; then
        local local_dns
        local_dns="$(awk '/^# Interface wan$/ {getline; print $2}' /var/resolv.conf.auto)"
        if [ x"$local_dns" = x ]; then
            exit
        fi
        touch "$conf"
        local domain
        (zcat /etc/chn-domains.gz; cat /etc/chn-domains-extra) | grep -Ev '(^#|^\s*$)' | while read domain
        do
            echo "server=/$domain/${local_dns}"
        done >> $conf
        if [ "$(uci -q get shadowsocks.@global[0].global_server)" != 'nil' ]; then
            grep -Ev '(^#|^\s*$)' /etc/chn-domains-extra | while read domain
            do
                echo "ipset=/$domain/ss_spec_wan_ac"
            done >> $conf
        fi
        local remote_dns
        remote_dns="$(uci -q get dhcp.@dnsmasq[0].remote_dns)"
        printf "no-resolv\nserver=%s\n" "$remote_dns" >> $conf
        /etc/init.d/dnsmasq restart
    elif [ "$ACTION" = "ifdown" -a -e "$conf" ]; then
        rm $conf
        /etc/init.d/dnsmasq restart
    fi
}

case "$INTERFACE" in
    wan)
        update_dnsmasq
    ;;
esac
