#!/bin/sh

DNS_SERVER='2001:4860:4860::8888'

case "$INTERFACE" in
    wan6|wan_6|henet)
        local conf=/var/dnsmasq.d/ipv6-domains.conf
        if [ "$ACTION" = "ifup" -a ! -e "$conf" ]; then
            local domain
            grep -Ev '(^#|^\s*$)' /etc/ipv6-domains | while read domain
            do
                echo "server=/$domain/${DNS_SERVER}"
            done > $conf
            /etc/init.d/dnsmasq restart
        elif [ "$ACTION" = "ifdown" -a -e "$conf" ]; then
            local iface_wan6
            . /lib/functions/network.sh
            network_find_wan6 iface_wan6
            if [ x"$iface_wan6" = x ]; then
                rm $conf
                /etc/init.d/dnsmasq restart
            fi
        fi
        ;;
esac

exit

# When wan/pppoe is up
if [ "$INTERFACE" = "wan" ] && [ "$ACTION" = "ifup" ] \
       && [ "$(uci -q get network.wan.proto)" = "pppoe" ] \
       && [ "$(uci -q get network.wan6.proto)" = "6in4" ]; then

    . /usr/lib/ddns/dynamic_dns_functions.sh

    local tunnelid username password updatekey

    tunnelid="$(uci -q get network.wan6.tunnelid)"
    username="$(uci -q get network.wan6.username)"
    password="$(uci -q get network.wan6.password)"
    updatekey="$(uci -q get network.wan6.updatekey)"

    [ -n "$tunnelid" -a -n "$username" -a \( -n "$password" -o -n "$updatekey" \) ] && {
        [ -n "$updatekey" ] && password="$updatekey"

        local url="http://ipv4.tunnelbroker.net/nic/update?username=$username&password=$password&hostname=$tunnelid"
        local try=0
        local max=5

        while [ $((++try)) -le $max ]; do
            ( exec wget -qO- "$url" 2>/dev/null | grep -qF "$(get_current_ip)" ) &
            local pid=$!
            ( sleep 10; kill $pid 2>/dev/null ) &
            wait $pid && break
        done
    }

fi
