#!/bin/sh

DNS_SERVER='2001:4860:4860::8888'

case "$INTERFACE" in
    wan6|wan_6|henet)
        local conf=/var/dnsmasq.d/99-ipv6-domains.conf
        if [ "$ACTION" = "ifup" -a ! -e "$conf" ]; then
            local domain
            grep -Ev '(^#|^\s*$)' /etc/ipv6-domains | while read domain
            do
                echo "server=/$domain/${DNS_SERVER}"
            done > $conf
            /etc/init.d/dnsmasq restart
        elif [ "$ACTION" = "ifdown" -a -e "$conf" ]; then
            local iface_wan6
            . /lib/functions/network.sh
            network_find_wan6 iface_wan6
            if [ x"$iface_wan6" = x ]; then
                rm $conf
                /etc/init.d/dnsmasq restart
            fi
        fi
        ;;
esac
