#!/bin/sh

update_dnsmasq() {
    local conf
    conf=/tmp/dnsmasq.d/99-chn-domains.conf
    chn_domains=/var/run/dnsmasq/chn-domains
    if [ "$ACTION" = "ifup" ] && [ ! -e "$conf" ]; then
        local local_dns
        local_dns="$(awk '/^# Interface wan$/ {getline; print $2}' /var/resolv.conf.d/resolv.conf.auto)"
        if [ x"$local_dns" = x ]; then
            exit
        fi
        touch "$conf"
        local domain
        (zcat /etc/chn-domains.gz; cat /etc/chn-domains-extra) | grep -Ev '(^#|^\s*$)' | while read -r domain
        do
            echo "server=/$domain/${local_dns}"
        done >> "$chn_domains"
        if [ -x /etc/init.d/shadowsocks-libev ] && /etc/init.d/shadowsocks-libev enabled && [ "$(uci -q get shadowsocks-libev.ss_rules.disabled)" != '1' ]; then
            grep -Ev '(^#|^\s*$)' /etc/chn-domains-extra | while read domain
            do
                echo "ipset=/$domain/ss_rules_dst_bypass"
            done >> $conf
        fi
        local remote_dns
        remote_dns="$(uci -q get dhcp.@dnsmasq[0].remote_dns)"
        printf "no-resolv\nserver=%s\n" "$remote_dns" >> $conf
        /etc/init.d/dnsmasq restart
    elif [ "$ACTION" = "ifdown" ] && [ -e "$conf" ]; then
        rm "$chn_domains"
        rm "$conf"
        /etc/init.d/dnsmasq restart
    fi
}

case "$INTERFACE" in
    wan)
        update_dnsmasq
    ;;
esac
